# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Munro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gaelic_name', models.TextField(blank=True, null=True)),
                ('heightm', models.IntegerField()),
                ('heightf', models.IntegerField()),
                ('grid_letters', models.CharField(db_column='map', max_length=2)),
                ('altmap', models.CharField(max_length=2)),
                ('grid', models.CharField(max_length=2)),
                ('easting', models.IntegerField()),
                ('northing', models.IntegerField()),
                ('trigpoint', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('hiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munros.Hiker')),
                ('munro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munros.Munro')),
            ],
        ),
    ]
