# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munro',
            name='altmap',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
